services:
  - type: web
    name: mini-cart-php
    env: php
    branch: main
    region: oregon
    plan: free
    buildCommand: |
      composer install --no-interaction --prefer-dist
      cp .env.example .env
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
