services:
  - type: web_service
    name: level-cart-php-fallback
    env: php
    branch: main
    region: oregon
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 index.php
